#!/usr/bin/env bash

## Run on ubuntu container to build packages

set -eu
APART_VERSION=""
APART_SHA256=""
while test $# -gt 0; do
  case "$1" in
    --version*)
      APART_VERSION=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    --sha256*)
      # sha256sum of tar file, ie 0.11 had f19b7f34bf6f1e62e82fca54a202142a4ab100344f2e88920e3032abff4eaba8
      APART_SHA256=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
  esac
done

if [ -z "$APART_VERSION" ] || [ -z "$APART_SHA256" ]; then
  echo "Required arguments --version=VERSION --sha256=HASH"
  exit 1
fi

apt update
apt install -y ruby-dev build-essential git libzmq3-dev curl pkg-config python3 rpm
if ! command -v fpm >/dev/null 2>&1; then
  gem install dotenv -v 2.8.1
  gem install fpm
fi

if [ ! -f  ~/.cargo/env ]; then
  curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
  source ~/.cargo/env
else
  source ~/.cargo/env
  rustup update
fi

rm -rf apart-gtk/
rm -rf /tmp/installdir

echo "Downloading & verifying apart-gtk-v$APART_VERSION ..."
curl -o apart.tar.gz -L https://github.com/alexheretic/apart-gtk/archive/refs/tags/v$APART_VERSION.tar.gz
echo "$APART_SHA256 apart.tar.gz" | sha256sum -c
tar xf apart.tar.gz
cd apart-gtk-$APART_VERSION

make
mkdir -p /tmp/installdir
make install DESTDIR=/tmp/installdir

cd /

fpm -s dir -t deb -n apart-gtk -v $APART_VERSION -C /tmp/installdir \
 -p apart-gtk_VERSION_ARCH.deb \
 -d policykit-1 \
 -d "partclone >= 0.2.89" \
 -d pigz \
 -d zstd \
 -d liblz4-tool \
 -d "python3-humanize >= 0.5.1" \
 -d "python3-zmq >= 15.3.0" \
 -d "python3-yaml >= 3.11" \
 -d "libgtk-3-0 >= 3.22" \
 --license "GPL-3" \
 -m "Alex Butler <alexheretic@gmail.com>" \
 --url "https://github.com/alexheretic/apart-gtk" \
 --description "GUI for cloning & restoring disk partitions to & from compressed image files" \
 usr/bin usr/lib usr/share

fpm -s dir -t rpm -n apart-gtk -v $APART_VERSION -C /tmp/installdir \
 -p apart-gtk-VERSION-1.ARCH.rpm \
 -d polkit \
 -d "partclone >= 0.2.89" \
 -d pigz \
 -d lz4 \
 -d "zstd >= 1.2.0" \
 -d "python3-humanize >= 0.5.1" \
 -d "python3-zmq >= 15.3.0" \
 -d "python3-yaml >= 3.11" \
 -d "gtk3 >= 3.22" \
 --license "GPL-3" \
 -m "Alex Butler <alexheretic@gmail.com>" \
 --url "https://github.com/alexheretic/apart-gtk" \
 --description "GUI for cloning & restoring disk partitions to & from compressed image files" \
 usr/bin usr/lib usr/share
