#!/usr/bin/env bash

set -eu
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOCKER_NAME="apart-docker-build-deb"
APART_VERSION=""
APART_SHA256=""
while test $# -gt 0; do
  case "$1" in
    --version*)
      APART_VERSION=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
    --sha256*)
      APART_SHA256=`echo $1 | sed -e 's/^[^=]*=//g'`
      shift
      ;;
  esac
done

if [ -z "$APART_VERSION" ] || [ -z "$APART_SHA256" ]; then
  echo "Required arguments --version=VERSION --sha256=HASH"
  exit 1
fi

docker run --rm --name $DOCKER_NAME -d ubuntu:17.04 tail -f /dev/null
docker cp $DIR/build-deb $DOCKER_NAME:/
docker exec -t $DOCKER_NAME ./build-deb --version=$APART_VERSION --sha256=$APART_SHA256
docker cp $DOCKER_NAME:/apart-gtk_${APART_VERSION}_amd64.deb ./
(docker stop $DOCKER_NAME >/dev/null 2>&1 &)

gpg --armor --detach-sign apart-gtk_${APART_VERSION}_amd64.deb
