#!/usr/bin/env bash

## Assume was called with expected args '-Jbo name,size,fstype,label,mountpoint'
echo '{
   "blockdevices": [
      {"name": "sdx", "size": 750156374016, "fstype": null, "label": null, "mountpoint": null, "uuid": null,
         "children": [
            {"name": "sdx1", "size": 104857600, "fstype": "ntfs", "label": "win reserved", "mountpoint": null, "uuid": "123-123-123"},
            {"name": "sdx2", "size": 536766054400, "fstype": "ntfs", "label": "ssd", "mountpoint": null, "uuid": "234-234-234"},
            {"name": "sdx3", "size": 181070200832, "fstype": "ext4", "label": "arch", "mountpoint": "/", "uuid": "345-345-345"},
            {"name": "sdx4", "size": 1024, "fstype": null, "label": null, "mountpoint": null, "uuid": null},
            {"name": "sdx5", "size": 32212254720, "fstype": null, "label": null, "mountpoint": null, "uuid": null}
         ]
      },
      {"name": "sdy", "size": 62109253632, "fstype": null, "label": null, "mountpoint": null, "uuid": null,
         "children": [
            {"name": "sdy1", "size": 524288000, "fstype": "ext2", "label": "boot", "mountpoint": null, "uuid": "456-456-456"},
            {"name": "sdy2", "size": 2147483648, "fstype": "swap", "label": "swap", "mountpoint": null, "uuid": "567-567-567"},
            {"name": "sdy3", "size": 59436433408, "fstype": "f2fs", "label": "main", "mountpoint": null, "uuid": "678-678-678"}
         ]
      }
   ]
}'
