#!/usr/bin/env bash

set -eu
CARGO_CMD="rustup run stable cargo"
while test $# -gt 0; do
  case "$1" in
    --cargo-cmd*)
      CARGO_CMD=$(echo "$1" | sed -e 's/^[^=]*=//g')
      shift
      ;;
  esac
done

APART_CORE_VERSION="0.3.6"
APART_CORE_SHA256='614d40cecceef832aa38e33a80ff96a0723449e359a7529bd9e863a4d01aed57'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "$DIR"
rm -rf target
mkdir -p "$DIR"/target/lib/apart-gtk/src

echo "Building apart-core $APART_CORE_VERSION"
cd "$DIR"/target
curl -o core.tar.gz -L https://github.com/alexheretic/apart-core/archive/v$APART_CORE_VERSION.tar.gz
echo "$APART_CORE_SHA256 core.tar.gz" | sha256sum -c
tar xf core.tar.gz
(cd apart-core-$APART_CORE_VERSION && $CARGO_CMD build --release)
cp apart-core-$APART_CORE_VERSION/target/release/apart-core lib/apart-gtk/
strip lib/apart-gtk/apart-core
rm core.tar.gz
rm -rf apart-core-$APART_CORE_VERSION


echo 'Copy & compile sources'
cd "$DIR"/target/lib/apart-gtk/src
cp -r "$DIR"/src/* ./
python3 -m compileall ./


echo 'Copy misc & icons'
cd "$DIR"/target
mkdir -p share/applications
cp "$DIR"/misc/*.desktop share/applications/
mkdir -p share/icons/hicolor/scalable/apps/
cp "$DIR"/icon/apart.svg share/icons/hicolor/scalable/apps/
mkdir -p share/icons/hicolor/48x48/apps/
cp "$DIR"/icon/apart.png share/icons/hicolor/48x48/apps/
mkdir -p share/polkit-1/actions
cp "$DIR"/misc/*.policy share/polkit-1/actions/
mkdir -p bin
ln -s ../lib/apart-gtk/src/app.py bin/apart-gtk


command -v tree >/dev/null 2>&1 && tree "$DIR"/target || true
