#!/usr/bin/env bash

set -eu
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(cd $dir/apart-core && cargo build)

if [ -f ~/.config/apart-gtk/history.yaml ]; then
  cp ~/.config/apart-gtk/history.yaml $dir/history.yaml.backup
fi

RUST_BACKTRACE=full \
  APART_GTK_CORE_CMD=$dir/apart-core/target/debug/apart-core \
  RUST_LOG=info \
  $dir/src/app.py
