#!/usr/bin/env bash

set -eu
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f $dir/apart-core/target/debug/apart-core ]; then
  (cd $dir/apart-core && cargo build)
fi

RUST_BACKTRACE=1 \
  APART_PARTCLONE_CMD=$dir/test/mockpcl \
  APART_GTK_CORE_CMD=$dir/apart-core/target/debug/apart-core \
  RUST_LOG=info \
  APART_LSBLK_CMD=$dir/test/mocklsblk \
  $dir/src/app.py
